services:
  find-a-friend-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=courses
      - POSTGRESQL_PASSWORD=@ignite
      - POSTGRESQL_DATABASE=apibarbershop